# 1. 리스트와 튜플
- 공통점
1. 슬라이싱[start:end:step], 인덱싱[i] 가능
2. for 문으로 순회 가능
- 차이점
1. 리스트의 요소는 바꿀수 있으나 튜플의 요소는 바꿀 수 없어, 리스트는 사전의 Key로 사용할 수 없지만, 튜플은 사전의 key로 사용 가능
2. 순회속도는 튜플이 약간 더 빠름 => 데이터가 큰 경우에 한해서, 리스트로 작업 후, 튜플로 자료형을 바꾼 후 순회
- 리스트 관련함수 : append(x), insert(a, x), remove(x), pop(), index(x), +, extend(list2)

In [9]:
# 순회 속도 비교하기 : 거의 비슷...?
import time

large_L = list(range(100000))
large_T = tuple(range(100000))

start_time = time.time()
for va1l in large_L:
    pass
end_time = time.time()
print("list ", end_time - start_time)

start_time = time.time()
for val2 in large_T:
    pass
end_time = time.time()
print("tuple ", end_time - start_time)

list  0.0038051605224609375
tuple  0.005181074142456055


In [18]:
# 리스트 관련 함수
l = [4,5,1,2,10]
l.append(15)
l.insert(1, 7)
l.insert(1,1)
l.remove(1)
print(l)
print(l.index(2))

[4, 7, 5, 1, 2, 10, 15]
4


# 2. 딕셔너리
- 키와 값 쌍으로 이루어진 테이블
- 관련 함수 : .keys(), .values(), items()

In [21]:
dic = {1:1, 2:4, 3:9, 4:16}
dic[5] = 20 # 새로운 요소 추가
print(dic)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 20}


In [22]:
print(dic.items())

dict_items([(1, 1), (2, 4), (3, 9), (4, 16), (5, 20)])


In [25]:
for key, val in dic.items():
    print(key, val)

for key in dic.keys():
    dic[key] = dic[key] * 0.5
print(dic)

1 0.5
2 2.0
3 4.5
4 8.0
5 10.0
{1: 0.25, 2: 1.0, 3: 2.25, 4: 4.0, 5: 5.0}


# 3. 반복문과 Comprehension
- 이터레이터 객체 생성
1. range(start, end, stop)
    - 값을 하나만 넣으면 end, 두 개를 넣으면 end
2. itertools 모듈 함수
    - itertools.product(*L) : 순회 가능한 여러개의 객체를 순서대로 순회하는 이터레이터 성생
    - itertools.combiniations(p, r) : 이터레이터 객체 p에서 크기 r의 가능한 모든 조합
    - itertools.permutations(p, r) : 이터레이터 객체 p에서 크기 r의 가능한 모든 순열    
- list comprehension : [output for element iterator if 조건]
- dictionary comprehension : {key : value for key, val in iterator if 조건}

In [26]:
import itertools

cnt = 0
for a,b,c in itertools.product(range(5), range(5), range(5)):
    print(a,b,c)

0 0 0
0 0 1
0 0 2
0 0 3
0 0 4
0 1 0
0 1 1
0 1 2
0 1 3
0 1 4
0 2 0
0 2 1
0 2 2
0 2 3
0 2 4
0 3 0
0 3 1
0 3 2
0 3 3
0 3 4
0 4 0
0 4 1
0 4 2
0 4 3
0 4 4
1 0 0
1 0 1
1 0 2
1 0 3
1 0 4
1 1 0
1 1 1
1 1 2
1 1 3
1 1 4
1 2 0
1 2 1
1 2 2
1 2 3
1 2 4
1 3 0
1 3 1
1 3 2
1 3 3
1 3 4
1 4 0
1 4 1
1 4 2
1 4 3
1 4 4
2 0 0
2 0 1
2 0 2
2 0 3
2 0 4
2 1 0
2 1 1
2 1 2
2 1 3
2 1 4
2 2 0
2 2 1
2 2 2
2 2 3
2 2 4
2 3 0
2 3 1
2 3 2
2 3 3
2 3 4
2 4 0
2 4 1
2 4 2
2 4 3
2 4 4
3 0 0
3 0 1
3 0 2
3 0 3
3 0 4
3 1 0
3 1 1
3 1 2
3 1 3
3 1 4
3 2 0
3 2 1
3 2 2
3 2 3
3 2 4
3 3 0
3 3 1
3 3 2
3 3 3
3 3 4
3 4 0
3 4 1
3 4 2
3 4 3
3 4 4
4 0 0
4 0 1
4 0 2
4 0 3
4 0 4
4 1 0
4 1 1
4 1 2
4 1 3
4 1 4
4 2 0
4 2 1
4 2 2
4 2 3
4 2 4
4 3 0
4 3 1
4 3 2
4 3 3
4 3 4
4 4 0
4 4 1
4 4 2
4 4 3
4 4 4


In [27]:
for a,b,c in zip(range(5), range(5), range(5)):
    print(a,b,c)

0 0 0
1 1 1
2 2 2
3 3 3
4 4 4


In [31]:
l = ["a","b","c","d"]
for comb in itertools.combinations(l,3):
    print(comb)

('a', 'b', 'c')
('a', 'b', 'd')
('a', 'c', 'd')
('b', 'c', 'd')


In [32]:
l = [x**2 for x in range(10) if x%2 == 0]
l

[0, 4, 16, 36, 64]

In [33]:
X = [1,2,3,'a', 'b']
Y = [3,1,2,'c',4]
l = [x+y for x,y in itertools.product(X,Y) if type(x)==type(y)==int]
print(l)

[4, 2, 3, 5, 5, 3, 4, 6, 6, 4, 5, 7]


In [34]:
dic = {1:'NaN', 2:2, 3:4, 4:'NaN'}
dic2 = {x:y for x, y in dic.items() if y != 'NaN'}
dic2

{2: 2, 3: 4}

# 4. Numpy Data Structure
- 효율적인 배열 연산을 위해 개발

In [6]:
import numpy as np

print("np.zeros(10, dtype = int):\n", np.zeros(10, dtype=int))
print("\nnp.ones((3, 5), dtype = float):\n", np.ones((3,5), dtype=float))
print("\nnp.full((3,5), 3.14):\n", np.full((3,5), 3.14))
print("\nnp.arange(0, 20, 2):\n", np.arange(0, 20, 2))
print("\nnp.linspace(0, 1, 5):\n", np.linspace(0,1,5))
print("\nnp.random.random((3,3)):\n", np.random.random((3,3)))
print("\nnp.random.normal(0, 1, (3, 3)):\n", np.random.normal(0, 1, (3,3)))
print("\nnp.random.randint(0, 10, (3, 3)):\n", np.random.randint(0, 10, (3,3)))
print("\nnp.eye(3):\n", np.eye(3))

np.zeros(10, dtype = int):
 [0 0 0 0 0 0 0 0 0 0]

np.ones((3, 5), dtype = float):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

np.full((3,5), 3.14):
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]

np.arange(0, 20, 2):
 [ 0  2  4  6  8 10 12 14 16 18]

np.linspace(0, 1, 5):
 [0.   0.25 0.5  0.75 1.  ]

np.random.random((3,3)):
 [[0.07351308 0.736391   0.28344039]
 [0.282523   0.92645362 0.75957073]
 [0.22212444 0.50195743 0.88034966]]

np.random.normal(0, 1, (3, 3)):
 [[ 2.34562639 -0.10205295 -1.8663468 ]
 [-0.07840066 -1.13730109  2.22371358]
 [ 1.94213797 -0.17979095 -0.03331728]]

np.random.randint(0, 10, (3, 3)):
 [[9 7 8]
 [7 9 2]
 [9 4 9]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 2차원 배열의 인덱싱 및 슬라이싱
x2 = np.random.random(size = (10, 5))

print("x2[0, 1]", x2[0, 1])
print("x2[1:4, 2]\n", x2[1:4, 2])
print("x2[0, 2:4]\n", x2[0, 2:4])
print("x2[0:3, 2:4]\n", x2[0:3, 2:4])

x2[0, 1] 0.9313436694226871
x2[1:4, 2]
 [0.3903141  0.5721617  0.70085865]
x2[0, 2:4]
 [0.29631304 0.48550378]
x2[0:3, 2:4]
 [[0.29631304 0.48550378]
 [0.3903141  0.66644969]
 [0.5721617  0.03805244]]


### 유니버설 함수

In [8]:
# 사용 기초
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])

print("x + y = ", x + y)
print("x - y = ", x - y)
print("x * y = ", x * y)
print("x / y = ", x / y)
print("log x = ", np.log(x))

x + y =  [5 5 5 5]
x - y =  [-3 -1  1  3]
x * y =  [4 6 6 4]
x / y =  [0.25       0.66666667 1.5        4.        ]
log x =  [0.         0.69314718 1.09861229 1.38629436]


In [12]:
import time

# 루프와 유니버설 함수의 속도 비교
arr_1 = np.random.randint(1, 10, size = 10 ** 8)
arr_2 = np.random.randint(1, 10, size = 10 ** 8)

### 리스트를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = []
for va1, val2 in zip(arr_1, arr_2):
    output.append(val1+val2)
t2 = time.time()
print("반복문을 사용한 경우:", round(t2 - t1, 4))
### 유니버설 함수를 사용하여 벡터의 덧셈 구현
t1 = time.time()
output = arr_1 + arr_2
t2 = time.time()
print("유니버설 함수를 사용한 경우:", round(t2 - t1, 4))

반복문을 사용한 경우: 44.4359
유니버설 함수를 사용한 경우: 7.9511


In [16]:
# 브로드 캐스팅 : 다른 크기의 배열에 유니버설 함수 적용, 큰 차원의 배열에 맞게 작은 배열 확장
print("np.arrange(3) + 5:", np.arange(3)+5, '\n')
print("np.ones((3,3)) + np.arange(3)\n", np.ones((3,3)) + np.arange(3), '\n')
print("np.arange(3).reshape(3,1) + np.arange(3)\n", np.arange(3).reshape(3,1) + np.arange(3))

np.arrange(3) + 5: [5 6 7] 

np.ones((3,3)) + np.arange(3)
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] 

np.arange(3).reshape(3,1) + np.arange(3)
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [17]:
# z-normalization
X = np.random.random((10, 3))
Xmean = X.mean(axis=0)
Xstd = X.std(axis=0)

Z = (X-Xmean) / Xstd
print("Z: \n", Z)

Z: 
 [[-0.09185379 -1.21886949  1.58410704]
 [-0.64041408 -0.48142411  0.78155086]
 [ 0.49308475 -0.59493745 -0.78531182]
 [ 1.56759254 -0.08632112  0.51798183]
 [-0.93582921  0.82553516  0.7857849 ]
 [-0.64093119  1.05478311  1.04691135]
 [ 0.51003575  0.4024175  -1.2704861 ]
 [ 1.68024058  1.95734337 -0.43501383]
 [-1.53020444 -1.38032679 -1.13951068]
 [-0.41172093 -0.47820018 -1.08601357]]


In [20]:
# 비교 연산자
L = np.array([1, 2, 3, 4, 5])
cond = L >= 3
print(sum(cond)) # 조건을 만족하는 요소의 개수
print(L[cond])

3
[3 4 5]


# Pandas Data Structure
- series : 1차원 배열 자료형으로, 인덱스와 값의 쌍으로 구성
- dataframe : 2차원 배열으로 값, 행 인덱스, 열 인덱스로 구성
- loc (맨뒤 값 포함), iloc(맨 뒤 값 포함안함)

In [22]:
import pandas as pd

S = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
df = pd.DataFrame({"col1": [1, 2, 3, 4],
                  "col2": [5, 6, 7, 8]}, 
                  index = ['a', 'b', 'c', 'd'])

df.iloc[3:20, 2:4] = 'Changed2'
df.iloc[:25]

col1  col2
a     1     5
b     2     6
c     3     7
d     4     8